[palettes.wal]
color_fg0 = "#c3c7c8"
color_bg1 = "#0f2024"
color_bg3 = "#5e7074"
color_blue = "#4F614C"
color_aqua = "#6B8D58"
color_green = "#556C32"
color_orange = "#667833"
color_purple = "#6D8533"
color_red = "#47572D"
color_yellow = "#667833"
