[palettes.wal]
color_fg0 = "#c6c8c6"
color_bg1 = "#1e261b"
color_bg3 = "#687862"
color_blue = "#6C9658"
color_aqua = "#8EA158"
color_green = "#3B8544"
color_orange = "#748D49"
color_purple = "#8B9F31"
color_red = "#718B37"
color_yellow = "#748D49"
