[palettes.wal]
color_fg0 = "#c7c9c5"
color_bg1 = "#212817"
color_bg3 = "#6e7862"
color_blue = "#8D924C"
color_aqua = "#C1C65B"
color_green = "#7EC279"
color_orange = "#909738"
color_purple = "#9FA75B"
color_red = "#78874D"
color_yellow = "#909738"
