ln -sfn ~/dwmarch/dots/alacritty ~/.config/
ln -sfn ~/dwmarch/dots/mpd/ ~/.config/
ln -sfn ~/dwmarch/dots/mpv ~/.config/
ln -sfn ~/dwmarch/dots/picom ~/.config/
ln -sfn ~/dwmarch/dots/rofi ~/.config/
ln -sfn ~/dwmarch/dots/starship ~/.config/
ln -sfn ~/dwmarch/dots/.Xresources ~/
ln -sfn ~/dwmarch/dots/.bashrc ~/
ln -sfn ~/dwmarch/dots/wal ~/.config/